
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ProductName extends javax.swing.JFrame {

    /**
     * Creates new form ProductName
     */
    public ProductName() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabProd = new javax.swing.JLabel();
        jtfProd = new javax.swing.JTextField();
        jcbCat = new javax.swing.JComboBox<>();
        jtfPrice = new javax.swing.JTextField();
        jlabCat = new javax.swing.JLabel();
        jlabPrice = new javax.swing.JLabel();
        jlabFeedback = new javax.swing.JLabel();
        jSP = new javax.swing.JScrollPane();
        jtabProd = new javax.swing.JTable();
        jbutAdd = new javax.swing.JButton();
        jbutUpdate = new javax.swing.JButton();
        jbutDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabProd.setText("Product Name:");

        jtfProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jcbCat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FOOD", "ART", "ELECTRONIC", "ELECTRICITY" }));

        jtfPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlabCat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabCat.setText("Category:");

        jlabPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabPrice.setText("Price:");

        jlabFeedback.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jlabFeedback.setForeground(new java.awt.Color(255, 0, 0));

        jtabProd.setBackground(new java.awt.Color(102, 102, 102));
        jtabProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtabProd.setForeground(new java.awt.Color(153, 0, 0));
        jtabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Category", "Price"
            }
        ));
        jtabProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabProdMouseClicked(evt);
            }
        });
        jSP.setViewportView(jtabProd);

        jbutAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutAdd.setText("Add");
        jbutAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutAddActionPerformed(evt);
            }
        });

        jbutUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutUpdate.setText("Update");
        jbutUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutUpdateActionPerformed(evt);
            }
        });

        jbutDel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutDel.setText("Delete");
        jbutDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlabFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabProd))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfProd)
                            .addComponent(jtfPrice)
                            .addComponent(jcbCat, 0, 199, Short.MAX_VALUE)))
                    .addComponent(jSP)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbutAdd)
                            .addComponent(jlabCat))
                        .addGap(18, 18, 18)
                        .addComponent(jbutUpdate)
                        .addGap(26, 26, 26)
                        .addComponent(jbutDel)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabProd)
                    .addComponent(jtfProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabCat))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutDel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutAddActionPerformed
         //set to null
        jlabFeedback.setText(""); 
        
        DefaultTableModel model = (DefaultTableModel)jtabProd.getModel(); 
        //storing the table to name model
        
        if(!jtfProd.getText().trim().equals("")){
        
            //adding values to the table by getting text from text field
            model.addRow(new Object[]{jtfProd.getText().trim(),jcbCat.getSelectedItem().toString(),jtfPrice.getText().trim()}); 
        
        }else{
            //displaying text when nothing isn't entered in the text fields
            jlabFeedback.setText("Product name should not be left blank");
        }
        
    }//GEN-LAST:event_jbutAddActionPerformed

    private void jbutUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel)jtabProd.getModel();
        
        if(jtabProd.getSelectedRow() == -1){
            //nested loop
         
           if(jtabProd.getRowCount()== 0){
               jlabFeedback.setText("Table is empty");
            }else{
               jlabFeedback.setText("You must select a product");
            }
        }else{
          model.setValueAt(jtfProd.getText(),jtabProd.getSelectedRow(),0);
          model.setValueAt(jcbCat.getSelectedItem().toString(),jtabProd.getSelectedRow(),1);
          model.setValueAt(jtfPrice.getText(),jtabProd.getSelectedRow(),2);
        }
    }//GEN-LAST:event_jbutUpdateActionPerformed

    private void jbutDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutDelActionPerformed
         DefaultTableModel model = (DefaultTableModel)jtabProd.getModel();
         
         if(jtabProd.getSelectedRow() == -1){
         
            if(jtabProd.getRowCount()== 0){
                jlabFeedback.setText("Table is empty");
            }else{
                jlabFeedback.setText("You must select a product");
            }
        }else{
            model.removeRow(jtabProd.getSelectedRow());
        }
    }//GEN-LAST:event_jbutDelActionPerformed

    private void jtabProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabProdMouseClicked
         DefaultTableModel model = (DefaultTableModel)jtabProd.getModel();
         
         jtfProd.setText(model.getValueAt(jtabProd.getSelectedRow(),0).toString());
         jcbCat.setSelectedItem(model.getValueAt(jtabProd.getSelectedRow(), 1).toString());
         jtfPrice.setText(model.getValueAt(jtabProd.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_jtabProdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jSP;
    private javax.swing.JButton jbutAdd;
    private javax.swing.JButton jbutDel;
    private javax.swing.JButton jbutUpdate;
    private javax.swing.JComboBox<String> jcbCat;
    private javax.swing.JLabel jlabCat;
    private javax.swing.JLabel jlabFeedback;
    private javax.swing.JLabel jlabPrice;
    private javax.swing.JLabel jlabProd;
    private javax.swing.JTable jtabProd;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfProd;
    // End of variables declaration//GEN-END:variables
}
