/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 * 
 */
public class Restaurants extends javax.swing.JFrame {
 double firstnum;
 double secondnum;
 double result;
 String operations;
 double[] i= new double [5];
    /**
     * Creates new form Restaurants
     */
    public Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtDisplay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbut7 = new javax.swing.JButton();
        jbutAddMinus = new javax.swing.JButton();
        jbut8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jbutPlus = new javax.swing.JButton();
        jbutBackspace = new javax.swing.JButton();
        jbutCancel = new javax.swing.JButton();
        jbut6 = new javax.swing.JButton();
        jbut5 = new javax.swing.JButton();
        jbut9 = new javax.swing.JButton();
        jbut4 = new javax.swing.JButton();
        jbut1 = new javax.swing.JButton();
        jbut2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jbut0 = new javax.swing.JButton();
        jbutDot = new javax.swing.JButton();
        jbut3 = new javax.swing.JButton();
        jbutMinus = new javax.swing.JButton();
        jbutMulti = new javax.swing.JButton();
        jbutDiv = new javax.swing.JButton();
        jbutEquals = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaReciept = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jlabSTotal = new javax.swing.JLabel();
        jtfSTotal = new javax.swing.JTextField();
        jlabTax = new javax.swing.JLabel();
        jtfTax = new javax.swing.JTextField();
        jlabTotal = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbutTotal = new javax.swing.JButton();
        jbutReciept = new javax.swing.JButton();
        jbutReset = new javax.swing.JButton();
        jbutExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jlabCDrinks = new javax.swing.JLabel();
        jtfCDrink = new javax.swing.JTextField();
        jtfCDelivery = new javax.swing.JTextField();
        jlabCMeal = new javax.swing.JLabel();
        jlabCDelivery = new javax.swing.JLabel();
        jlabCostMeal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jcbBurger = new javax.swing.JCheckBox();
        jcbBacon = new javax.swing.JCheckBox();
        jcbBurgerMeal = new javax.swing.JCheckBox();
        jtfBurgerMeal = new javax.swing.JTextField();
        jtfBurger = new javax.swing.JTextField();
        jtfBacon = new javax.swing.JTextField();
        jcbDelivery = new javax.swing.JCheckBox();
        jcbTax = new javax.swing.JCheckBox();
        jcbDrink = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jcbMoney = new javax.swing.JComboBox<>();
        jtbConvert = new javax.swing.JToggleButton();
        jtfConvert = new javax.swing.JTextField();
        jtbClose = new javax.swing.JToggleButton();
        jLabConvert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESTAURANT MANAGEMENT");
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton1.setText("j");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jbut7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut7.setText("7");
        jbut7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut7ActionPerformed(evt);
            }
        });

        jbutAddMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutAddMinus.setText("+/-");
        jbutAddMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutAddMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutAddMinusActionPerformed(evt);
            }
        });

        jbut8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut8.setText("8");
        jbut8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut8ActionPerformed(evt);
            }
        });

        jButton13.setText("j");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton14.setText("j");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton15.setText("j");
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jbutPlus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutPlus.setText("+");
        jbutPlus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutPlusActionPerformed(evt);
            }
        });

        jbutBackspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutBackspace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBackspaceActionPerformed(evt);
            }
        });

        jbutCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutCancel.setText("C");
        jbutCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutCancelActionPerformed(evt);
            }
        });

        jbut6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut6.setText("6");
        jbut6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut6ActionPerformed(evt);
            }
        });

        jbut5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut5.setText("5");
        jbut5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut5ActionPerformed(evt);
            }
        });

        jbut9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut9.setText("9");
        jbut9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut9ActionPerformed(evt);
            }
        });

        jbut4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut4.setText("4");
        jbut4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut4ActionPerformed(evt);
            }
        });

        jbut1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut1.setText("1");
        jbut1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut1ActionPerformed(evt);
            }
        });

        jbut2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut2.setText("2");
        jbut2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut2ActionPerformed(evt);
            }
        });

        jButton10.setText("j");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton11.setText("j");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton12.setText("j");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jbut0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut0.setText("0");
        jbut0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut0ActionPerformed(evt);
            }
        });

        jbutDot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutDot.setText(".");
        jbutDot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutDotActionPerformed(evt);
            }
        });

        jbut3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbut3.setText("3");
        jbut3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut3ActionPerformed(evt);
            }
        });

        jbutMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutMinus.setText("-");
        jbutMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutMinusActionPerformed(evt);
            }
        });

        jbutMulti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutMulti.setText("*");
        jbutMulti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutMultiActionPerformed(evt);
            }
        });

        jbutDiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutDiv.setText("/");
        jbutDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutDivActionPerformed(evt);
            }
        });

        jbutEquals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbutEquals.setText("=");
        jbutEquals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutEqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbutBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbut1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbut4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbut7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbut0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbut8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbut9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbutCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutAddMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbut5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbut6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbut2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbut3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbutDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbutDot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbutEquals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(96, 96, 96))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jtDisplay)
                        .addGap(100, 100, 100))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbutBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutAddMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbut8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbut7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbut9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbutMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbut4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbut5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbut6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbut2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbut1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbut3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbut0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutDot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(774, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)))
        );

        jTabbedPane1.addTab("Calculator", jPanel7);

        jtaReciept.setColumns(20);
        jtaReciept.setRows(5);
        jScrollPane2.setViewportView(jtaReciept);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reciept", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlabSTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabSTotal.setText("Sub Total:");

        jtfSTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfSTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfSTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlabTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabTax.setText("Tax:");

        jtfTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfTax.setText("0");
        jtfTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlabTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabTotal.setText("Total:");

        jtfTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabTax, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabTax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jbutTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbutTotal.setText("Total");
        jbutTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutTotalMouseClicked(evt);
            }
        });

        jbutReciept.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbutReciept.setText("Reciept");
        jbutReciept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutReciept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutRecieptMouseClicked(evt);
            }
        });
        jbutReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutRecieptActionPerformed(evt);
            }
        });

        jbutReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbutReset.setText("Reset");
        jbutReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutResetMouseClicked(evt);
            }
        });
        jbutReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutResetActionPerformed(evt);
            }
        });

        jbutExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbutExit.setText("Exit");
        jbutExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbutExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbutTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jbutReciept, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jbutReset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jbutExit, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbutReciept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbutReset))
                    .addComponent(jbutTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbutExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlabCDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabCDrinks.setText("Cost of Drink:");

        jtfCDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfCDrink.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfCDrink.setText("0");
        jtfCDrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtfCDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfCDelivery.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfCDelivery.setText("0");
        jtfCDelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlabCMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabCMeal.setText("Cost of Meal:");

        jlabCDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabCDelivery.setText("Cost of Delivery:");

        jlabCostMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabCostMeal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlabCostMeal.setText("0");
        jlabCostMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlabCDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfCDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlabCDelivery)
                        .addGap(18, 18, 18)
                        .addComponent(jtfCDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlabCMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlabCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabCDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabCostMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabCMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabCDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jcbBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbBurger.setText("Burger");
        jcbBurger.setBorder(new javax.swing.border.MatteBorder(null));
        jcbBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbBurgerMouseClicked(evt);
            }
        });
        jcbBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBurgerActionPerformed(evt);
            }
        });

        jcbBacon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbBacon.setText("Bacon");
        jcbBacon.setBorder(new javax.swing.border.MatteBorder(null));
        jcbBacon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbBaconMouseClicked(evt);
            }
        });
        jcbBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBaconActionPerformed(evt);
            }
        });

        jcbBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbBurgerMeal.setText(" Burger Meal");
        jcbBurgerMeal.setBorder(new javax.swing.border.MatteBorder(null));
        jcbBurgerMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbBurgerMealMouseClicked(evt);
            }
        });
        jcbBurgerMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBurgerMealActionPerformed(evt);
            }
        });

        jtfBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBurgerMeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfBurgerMeal.setText("0");
        jtfBurgerMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtfBurgerMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBurgerMealActionPerformed(evt);
            }
        });

        jtfBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBurger.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfBurger.setText("0");
        jtfBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtfBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBurgerActionPerformed(evt);
            }
        });

        jtfBacon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBacon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfBacon.setText("0");
        jtfBacon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtfBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBaconActionPerformed(evt);
            }
        });

        jcbDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbDelivery.setText("Home Delivery");
        jcbDelivery.setBorder(new javax.swing.border.MatteBorder(null));
        jcbDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbDeliveryMouseClicked(evt);
            }
        });
        jcbDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDeliveryActionPerformed(evt);
            }
        });

        jcbTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbTax.setText("Tax");
        jcbTax.setBorder(new javax.swing.border.MatteBorder(null));
        jcbTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbTaxMouseClicked(evt);
            }
        });
        jcbTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTaxActionPerformed(evt);
            }
        });

        jcbDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a drink", "Orange juice", "Coffee", "Tea", "Cola", "Apple juice" }));
        jcbDrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDrinkActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4.setText("Drink");
        jTextField4.setBorder(new javax.swing.border.MatteBorder(null));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jcbTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbDelivery))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbBurger)
                            .addComponent(jcbBurgerMeal)
                            .addComponent(jcbBacon))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtfBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jtfBacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jcbBurgerMeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbBurger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbBacon)))
                .addGap(62, 62, 62)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDelivery)
                    .addComponent(jcbTax))
                .addGap(28, 28, 28))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jcbMoney.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbMoney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Naira", "Dollar", "Pounds", "Yen", "Canadian Dollar", " " }));
        jcbMoney.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcbMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMoneyActionPerformed(evt);
            }
        });

        jtbConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtbConvert.setText("Convert");
        jtbConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtbConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbConvertActionPerformed(evt);
            }
        });

        jtfConvert.setBackground(new java.awt.Color(204, 204, 204));
        jtfConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtbClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtbClose.setText("Close");
        jtbClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtbConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jtbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabConvert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfConvert, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcbMoney, javax.swing.GroupLayout.Alignment.LEADING, 0, 190, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jcbMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfConvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 898, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBurgerActionPerformed

    private void jcbBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBaconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBaconActionPerformed

    private void jcbBurgerMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBurgerMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBurgerMealActionPerformed

    private void jcbDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDeliveryActionPerformed

    private void jcbTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTaxActionPerformed
              
        double iTotal1= Double.parseDouble(jtfCDrink.getText());
        double iTotal2= Double.parseDouble(jlabCostMeal.getText());
        double iTotal3= Double.parseDouble(jtfCDelivery.getText());
        
        double subTotal = ( iTotal1 + iTotal2 + iTotal3)/100;
        String pTotal = String.format(" %.2f", subTotal); 
        jtfTax.setText(pTotal ); 
       
    }//GEN-LAST:event_jcbTaxActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jbut9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut9ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut9.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut9ActionPerformed

    private void jbut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut6ActionPerformed
        String Enternumber= jtDisplay.getText()+jbut6.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut6ActionPerformed

    private void jbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut1ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut1.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut1ActionPerformed

    private void jbut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut7ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut7.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut7ActionPerformed

    private void jbut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut8ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut8.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut8ActionPerformed

    private void jbut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut4ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut4.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut4ActionPerformed

    private void jbut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut5ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut5.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut5ActionPerformed

    private void jbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut2ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut2.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut2ActionPerformed

    private void jbut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut3ActionPerformed
      String Enternumber= jtDisplay.getText()+jbut3.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut3ActionPerformed

    private void jbut0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut0ActionPerformed
        String Enternumber= jtDisplay.getText()+jbut0.getText();
      jtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbut0ActionPerformed

    private void jbutCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutCancelActionPerformed
      jtDisplay.setText(null);
    }//GEN-LAST:event_jbutCancelActionPerformed

    private void jbutBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBackspaceActionPerformed
        String backspace= null;
        if(jtDisplay.getText().length()>0){
        StringBuilder strC = new StringBuilder (jtDisplay.getText());
        strC.deleteCharAt(jtDisplay.getText().length()-1);
        backspace= strC.toString();
        jtDisplay.setText(backspace);
        
        }
    }//GEN-LAST:event_jbutBackspaceActionPerformed

    private void jbutDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutDivActionPerformed
      firstnum =Double.parseDouble(jtDisplay.getText());
      jtDisplay.setText("");
      operations= "/";
    }//GEN-LAST:event_jbutDivActionPerformed

    private void jbutMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutMultiActionPerformed
      firstnum =Double.parseDouble(jtDisplay.getText());
      jtDisplay.setText("");
      operations= "*";
    }//GEN-LAST:event_jbutMultiActionPerformed

    private void jbutMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutMinusActionPerformed
      firstnum =Double.parseDouble(jtDisplay.getText());
      jtDisplay.setText("");
      operations= "-";
    }//GEN-LAST:event_jbutMinusActionPerformed

    private void jbutPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutPlusActionPerformed
      firstnum =Double.parseDouble(jtDisplay.getText());
      jtDisplay.setText("");
      operations= "+";
    }//GEN-LAST:event_jbutPlusActionPerformed

    private void jbutDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutDotActionPerformed
        jtDisplay.setText(jtDisplay.getText()+ jbutDot.getText());
    }//GEN-LAST:event_jbutDotActionPerformed

    private void jbutAddMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutAddMinusActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtDisplay.getText()));
        ops = ops*(-1);
        jtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbutAddMinusActionPerformed

    private void jbutEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutEqualsActionPerformed
        String answer;
        secondnum = Double.parseDouble(jtDisplay.getText());
        if(operations== "+"){
        result = firstnum + secondnum;
        answer = String.format("%.2f",result);
        jtDisplay.setText(answer);
        }
        else if(operations== "-"){
        result= firstnum - secondnum;
        answer = String.format("%.2f",result);
        jtDisplay.setText(answer);
        }
        else if(operations== "*"){
        result= firstnum * secondnum;
        answer = String.format("%.2f",result);
        jtDisplay.setText(answer);
        }
         else if(operations== "/"){
        result= firstnum / secondnum;
        answer = String.format("%.2f",result);
        jtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jbutEqualsActionPerformed

    private void jtbConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbConvertActionPerformed
        final double Dollar= 300;
        final double Pounds =400;
        final double Yen=150;
        final double Canadian_Dollar=200;
        
        double Nigeria_Naira  = Double.parseDouble(jtfConvert.getText());
       if(jcbMoney.getSelectedItem().equals("Dollar")){
        String cConvert1 = String.format("N %.2f", Nigeria_Naira * Dollar );
        jLabConvert.setText(cConvert1); 
        } 
       if(jcbMoney.getSelectedItem().equals("Pounds")){
        String cConvert2 = String.format("N %.2f", Nigeria_Naira * Pounds );
        jLabConvert.setText(cConvert2); 
        } 
       if(jcbMoney.getSelectedItem().equals("Canada")){
        String cConvert3 = String.format("N %.2f", Nigeria_Naira * Canadian_Dollar );
        jLabConvert.setText(cConvert3); 
        } 
       if(jcbMoney.getSelectedItem().equals("Yen")){
        String cConvert4 = String.format("N %.2f", Nigeria_Naira * Yen);
        jLabConvert.setText(cConvert4); 
        } 
       
    }//GEN-LAST:event_jtbConvertActionPerformed

    private void jcbMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMoneyActionPerformed
       
    }//GEN-LAST:event_jcbMoneyActionPerformed

    private void jcbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDrinkActionPerformed
        double Tea = 1.20;
        double Apple_juice = 1.20;
        double Cola = 2.20;
        double Coffee = 1.60;
        double Orange_juice = 1.20;
       if(jcbDrink.getSelectedItem().equals("Select a drink")){
         jtfCDrink.setText(null); 
        }
       if(jcbDrink.getSelectedItem().equals("Tea")){
        String cTea = String.format(" %.2f",Tea );
        jtfCDrink.setText(cTea); 
        }
       if(jcbDrink.getSelectedItem().equals("Apple juice")){
        String cApplejuice = String.format(" %.2f",Apple_juice );
        jtfCDrink.setText(cApplejuice); 
         }
       if(jcbDrink.getSelectedItem().equals("Cola")){
        String cCola = String.format(" %.2f",Cola );
        jtfCDrink.setText(cCola); 
         }
       if(jcbDrink.getSelectedItem().equals("Coffee")){
        String cCoffee = String.format(" %.2f",Coffee );
        jtfCDrink.setText(cCoffee); 
         }
       if(jcbDrink.getSelectedItem().equals("Orange juice")){
        String cOrangejuice = String.format(" %.2f",Orange_juice );
       jtfCDrink.setText(cOrangejuice); 
       }        
              
    }//GEN-LAST:event_jcbDrinkActionPerformed

    private void jcbDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbDeliveryMouseClicked
        double iDelivery = 3.39;
        if(jcbDelivery.isSelected()){
        String pDelivery = String.format("%.2f", iDelivery);
        jtfCDelivery.setText(pDelivery);
        }
        else{
        jtfCDelivery.setText(null);       
        }
    }//GEN-LAST:event_jcbDeliveryMouseClicked

    private void jbutExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jbutExitActionPerformed

    private void jbutResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutResetActionPerformed
       
    }//GEN-LAST:event_jbutResetActionPerformed

    private void jbutResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutResetMouseClicked
         jtfBacon.setText(null);
     jtfBurger.setText(null);
     jtfBurgerMeal.setText(null);
     jtfCDelivery.setText(null);
     jtfCDrink.setText(null);
    jlabCostMeal.setText(null);
    jtfConvert.setText (null);
    jtfSTotal.setText(null);
    jtfTax.setText(null);
     jtfTotal.setText(null);
    }//GEN-LAST:event_jbutResetMouseClicked

    private void jcbBurgerMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbBurgerMealMouseClicked
      
        double cMeal = Double.parseDouble(jlabCostMeal.getText());
        double Burgermeal = Double.parseDouble(jtfBurgerMeal.getText());
        double iBurgermeal = 2.39;
        System.out.println(cMeal + " " +  " bmeal: " + Burgermeal);
        if(jcbBurgerMeal.isSelected())
        {
         i[0]= ((Burgermeal * iBurgermeal) + cMeal);
         String pMeal = String.format(" %.2f", i[0]);
         jlabCostMeal.setText(pMeal );
        }
    }//GEN-LAST:event_jcbBurgerMealMouseClicked

    private void jcbBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbBurgerMouseClicked
        
        double cMeal= Double.parseDouble(jlabCostMeal.getText());
        double Burger = Double.parseDouble(jtfBurger.getText());
        double iBurger= 4.50;
        System.out.println(cMeal + " " +  " bmeal: " + Burger);
        if(jcbBurger.isSelected())
        {
         i[1]= ((Burger * iBurger) + cMeal);
         String pMeal = String.format(" %.2f", i[1]);
         jlabCostMeal.setText(pMeal );
        }
    }//GEN-LAST:event_jcbBurgerMouseClicked

    private void jcbBaconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbBaconMouseClicked

        double cMeal= Double.parseDouble(jlabCostMeal.getText());
        double Bacon = Double.parseDouble(jtfBacon.getText());
        double iBacon= 2.39;
        System.out.println(cMeal + " " +  " bmeal: " + Bacon);
        if(jcbBacon.isSelected())
        {
         i[2]= ((Bacon * iBacon) + cMeal);
         String pMeal = String.format("%.2f", i[2]);
         jlabCostMeal.setText(pMeal );
        }
    }//GEN-LAST:event_jcbBaconMouseClicked

    private void jbutTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutTotalMouseClicked
        double iTotal1= Double.parseDouble(jtfCDrink.getText());
        double iTotal2= Double.parseDouble(jlabCostMeal.getText());
        double iTotal3= Double.parseDouble(jtfCDelivery.getText());
        double iTotal4= Double.parseDouble(jtfTax.getText());
       
        double subTotal = ( iTotal1 + iTotal2 + iTotal3);
        double allTotal = ( iTotal1 + iTotal2 + iTotal3 + iTotal4);
       
        String pTotal = String.format("%.2f", subTotal); 
        String sTotal = String.format(" %.2f", allTotal);
        jtfSTotal.setText(pTotal ); 
        jtfTotal.setText(sTotal );
    }//GEN-LAST:event_jbutTotalMouseClicked

    private void jcbTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbTaxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTaxMouseClicked

    private void jbutRecieptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutRecieptMouseClicked
      try{  double qty1= Double.parseDouble(jtfBacon.getText());
        double qty2= Double.parseDouble(jtfBurger.getText());
        double qty3= Double.parseDouble(jtfBurgerMeal.getText());
        double price1= Double.parseDouble(jlabCostMeal.getText());
        double price2= Double.parseDouble(jtfCDrink.getText());
        double price3= Double.parseDouble(jtfCDelivery.getText());
        double price4= Double.parseDouble(jtfTotal.getText());
        
        
        jtaReciept.append("\n\tRestaurant Management Systems:\n\n" + "Burger:\t\t"
                + qty2 + "\nBurger Meal:\t\t"+ 
                qty3 +"\nBacon:\t\t"+ qty1 + "\n Cost of meal:\t\t" + price1
                + "\n Cost of Drink:\t\t" + price2 + "\n Cost of Delivery:\t\t" + price3
                 + "\n Cost in total plus tax:\t\t" + price4 );
      }
      catch(Exception e){
       jtaReciept.append("Empty plate ");
      }
    }//GEN-LAST:event_jbutRecieptMouseClicked

    private void jtfBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBaconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBaconActionPerformed

    private void jtfBurgerMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBurgerMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBurgerMealActionPerformed

    private void jbutRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutRecieptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutRecieptActionPerformed

    private void jtfBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBurgerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabConvert;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbut0;
    private javax.swing.JButton jbut1;
    private javax.swing.JButton jbut2;
    private javax.swing.JButton jbut3;
    private javax.swing.JButton jbut4;
    private javax.swing.JButton jbut5;
    private javax.swing.JButton jbut6;
    private javax.swing.JButton jbut7;
    private javax.swing.JButton jbut8;
    private javax.swing.JButton jbut9;
    private javax.swing.JButton jbutAddMinus;
    private javax.swing.JButton jbutBackspace;
    private javax.swing.JButton jbutCancel;
    private javax.swing.JButton jbutDiv;
    private javax.swing.JButton jbutDot;
    private javax.swing.JButton jbutEquals;
    private javax.swing.JButton jbutExit;
    private javax.swing.JButton jbutMinus;
    private javax.swing.JButton jbutMulti;
    private javax.swing.JButton jbutPlus;
    private javax.swing.JButton jbutReciept;
    private javax.swing.JButton jbutReset;
    private javax.swing.JButton jbutTotal;
    private javax.swing.JCheckBox jcbBacon;
    private javax.swing.JCheckBox jcbBurger;
    private javax.swing.JCheckBox jcbBurgerMeal;
    private javax.swing.JCheckBox jcbDelivery;
    private javax.swing.JComboBox<String> jcbDrink;
    private javax.swing.JComboBox<String> jcbMoney;
    private javax.swing.JCheckBox jcbTax;
    private javax.swing.JLabel jlabCDelivery;
    private javax.swing.JLabel jlabCDrinks;
    private javax.swing.JLabel jlabCMeal;
    private javax.swing.JLabel jlabCostMeal;
    private javax.swing.JLabel jlabSTotal;
    private javax.swing.JLabel jlabTax;
    private javax.swing.JLabel jlabTotal;
    private javax.swing.JTextField jtDisplay;
    private javax.swing.JTextArea jtaReciept;
    private javax.swing.JToggleButton jtbClose;
    private javax.swing.JToggleButton jtbConvert;
    private javax.swing.JTextField jtfBacon;
    private javax.swing.JTextField jtfBurger;
    private javax.swing.JTextField jtfBurgerMeal;
    private javax.swing.JTextField jtfCDelivery;
    private javax.swing.JTextField jtfCDrink;
    private javax.swing.JTextField jtfConvert;
    private javax.swing.JTextField jtfSTotal;
    private javax.swing.JTextField jtfTax;
    private javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
